# Generated by Django 3.1.7 on 2021-04-15 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='NoneImage.jpg', null=True, upload_to='')),
                ('qr_code', models.ImageField(blank=True, default='NoneImage.jpg', upload_to='images/qr_codes')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('Кардиолог', 'Кардиолог'), ('Дерматолог', 'Дерматолог'), ('Терапевт', 'Терапевт'), ('Хирург', 'Хирург'), ('Оториноларинголог', 'Оториноларинголог'), ('Офтальмолог', 'Офтальмолог'), ('Онколог', 'Онколог'), ('Психотерапевт', 'Психотерапевт'), ('Педиатр', 'Педиатр'), ('Кардиолог', 'Кардиолог'), ('Ревматолог', 'Ревматолог'), ('Невролог', 'Невролог')], default='Cardiologist', max_length=50)),
                ('appointment_duration', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctorqueue',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='NoneImage.jpg', null=True, upload_to='images/profile-pic/PatientProfilePic')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('birthday', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 15, 17, 27, 7, 167974))),
                ('status', models.PositiveIntegerField(default=0, null=True)),
                ('membershipId', models.PositiveIntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
                ('Doctorqueue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctorqueue')),
            ],
            options={
                'ordering': ('membershipId',),
            },
        ),
        migrations.AddField(
            model_name='doctorqueue',
            name='patients',
            field=models.ManyToManyField(through='main.Membership', to='main.Patient'),
        ),
    ]
